---
- hosts: all
  sudo: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian

  tasks:
    - apt: "pkg={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim